/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimilarityTestRouteImport } from './routes/similarity-test'
import { Route as IndexRouteImport } from './routes/index'

const SimilarityTestRoute = SimilarityTestRouteImport.update({
  id: '/similarity-test',
  path: '/similarity-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/similarity-test': typeof SimilarityTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/similarity-test': typeof SimilarityTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/similarity-test': typeof SimilarityTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/similarity-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/similarity-test'
  id: '__root__' | '/' | '/similarity-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimilarityTestRoute: typeof SimilarityTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/similarity-test': {
      id: '/similarity-test'
      path: '/similarity-test'
      fullPath: '/similarity-test'
      preLoaderRoute: typeof SimilarityTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimilarityTestRoute: SimilarityTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
